# SESSION 5

## Task 1 — Install Transformers and Torch

In [3]:
%pip install transformers torch

In [4]:
import transformers
import torch

print("Transformers version:", transformers.__version__)
print("Torch version:", torch.__version__)

Transformers version: 5.16.1
Torch version: 2.11.0+cpu


## Task 2 — Limitation of Traditional NLP Models

Traditional NLP models such as Bag of Words and TF-IDF mainly represent text using individual words and their frequencies. They do not understand context very well, so a WhatsApp message with slang, spelling mistakes, sarcasm, or different word meanings can be difficult for these models to interpret correctly.

## Task 3 — Sentiment Analysis Using Hugging Face

Three sample Zomato/Swiggy-style review texts are used below. Replace them with actual recent reviews if required by your teacher.

## Task 4 — Transformer Model Other Than BERT

### RoBERTa

A popular transformer model for text classification is **RoBERTa (Robustly Optimized BERT Pretraining Approach)**.

1. RoBERTa is based on the BERT architecture but was trained with an improved training procedure and substantially more data.
2. Unlike the original BERT training setup, RoBERTa removes the Next Sentence Prediction objective and uses other training improvements to achieve stronger performance on many NLP tasks.

Hugging Face Model Hub: https://huggingface.co/models

## Task 5 — Basic Attention Mechanism

### Prompt used with ChatGPT

> Show a basic attention calculation example in Python using three short sentences as input. Use simple numerical vectors, calculate similarity scores with a dot product, and print the attention scores.

In [5]:
import numpy as np

def basic_attention(sentences):
    vectors = np.array([
        [1, 0, 1],
        [1, 1, 0],
        [0, 1, 1]
    ], dtype=float)

    attention_scores = np.dot(vectors, vectors.T)

    print("Input sentences:")
    for i, sentence in enumerate(sentences, start=1):
        print(f"{i}. {sentence}")

    print("\nAttention scores:")
    print(attention_scores)
    return attention_scores

sentences = [
    "I love this food",
    "The food is tasty",
    "The delivery was fast"
]

scores = basic_attention(sentences)

Input sentences:
1. I love this food
2. The food is tasty
3. The delivery was fast

Attention scores:
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


### Explanation of Attention Scores

Attention scores show how strongly one input is related to another according to the simple vector representation used in this example. A higher score means the two sentence vectors have greater similarity, so the model can give more attention to that relationship.

## Conclusion

This assignment demonstrates transformer libraries, sentiment analysis with a Hugging Face pipeline, a transformer model other than BERT, and a simple attention mechanism.